# Generated by Django 3.2.4 on 2022-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220528_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
