# Generated by Django 3.2.4 on 2022-05-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_customer_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
