# Generated by Django 3.2.4 on 2022-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220529_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='payment_method',
            field=models.CharField(choices=[('0', 'COD'), ('1', 'GCASH')], default='0', max_length=200),
        ),
    ]
