# Generated by Django 3.2.4 on 2022-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_shipping_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('GCASH', 'GCASH')], default='COD', max_length=200),
        ),
    ]
