# Generated by Django 3.2.4 on 2022-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_contactsus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactsUs',
            new_name='ContactUs',
        ),
    ]
